import { basicModule } from "./basic-lessons";
import type { FoundationReading } from "./foundation-types";

export type Lesson = {
  slug: string; title: string; minutes: number; intro: string;
  sections: { title: string; body: string; prompt?: string; slide?: { src: string; alt: string }; reading?: FoundationReading }[];
  presentation?: { download: string; attribution: string };
  example: { before?: string; after: string; caption: string };
  steps: string[]; task: string; placeholder: string;
  quiz: { question: string; options: string[]; answer: number; explanation: string };
  sources: { label: string; url: string }[];
};
export type CourseModule = { slug: string; number: string; title: string; subtitle: string; description: string; level: string; tags: string[]; lessons: Lesson[] };
const prompting = { label: "OpenAI · Escrever prompts", url: "https://learn.chatgpt.com/docs/prompting" };
const plugins = { label: "OpenAI · Plugins", url: "https://learn.chatgpt.com/docs/plugins" };
const skills = { label: "OpenAI · Criar skills", url: "https://learn.chatgpt.com/docs/build-skills" };
const work = { label: "OpenAI · Começar com Work", url: "https://learn.chatgpt.com/docs/get-started-with-work" };
const cron = { label: "OpenAI · Tarefas agendadas", url: "https://learn.chatgpt.com/docs/automations" };
const mcp = { label: "MCP · Introdução ao protocolo", url: "https://modelcontextprotocol.io/docs/getting-started/intro" };
const claude = { label: "Claude · Conectores", url: "https://claude.com/docs/connectors/overview" };
const computer = { label: "Claude · Computer use no Cowork", url: "https://support.claude.com/en/articles/14128542-let-claude-use-your-computer-in-cowork" };

const originalModules: CourseModule[] = [
  { slug: "fundamentos", number: "01", title: "IA, do zero à prática.", subtitle: "Entenda. Experimente. Aplique.", description: "Entenda o que está por trás da conversa e aprenda a transformar uma ideia em um prompt que funciona.", level: "Básico", tags: ["Conceitos", "LLMs", "Prompts"], lessons: [
    { slug: "o-que-e-ia", title: "Afinal, o que é IA?", minutes: 8,
      intro: "Você não precisa saber programar para usar IA. Precisa entender o que ela faz, onde ajuda e quando conferir o resultado.",
      sections: [
        { title: "Um sistema que aprende padrões", body: "Inteligência artificial é um campo que desenvolve sistemas capazes de realizar tarefas como reconhecer imagens, classificar informações e gerar texto. Muitos desses sistemas aprendem padrões a partir de exemplos. Um filtro de spam identifica mensagens suspeitas; uma IA generativa pode escrever o rascunho de uma resposta." },
        { title: "Comece por uma tarefa pequena", body: "Pense em algo repetitivo no seu negócio: organizar ideias para posts, transformar anotações em uma lista ou resumir um texto. Uma boa primeira tarefa tem uma entrada clara e uma saída que você consegue avaliar. A IA pode fazer o rascunho. A responsabilidade por usar esse rascunho continua sendo sua." },
        { title: "Fluência não é garantia de acerto", body: "Um texto pode parecer convincente e conter informações inventadas. Isso costuma ser chamado de alucinação. Peça que a IA indique o que falta saber e confira nomes, números e fatos na fonte. Para começar, use exemplos fictícios e informações públicas." }
      ],
      example: { before: "Faça meu marketing.", after: "Tenho uma loja fictícia de plantas. Sugira 5 ideias de posts para ensinar iniciantes a cuidar de suculentas. Para cada ideia, escreva um título e uma dica prática. Não invente dados de vendas.", caption: "Uma tarefa concreta é mais fácil de executar e de conferir." },
      steps: ["Escolha uma tarefa pequena do seu trabalho.", "Escreva quais informações você daria à IA.", "Defina como você saberia se a resposta está boa."], task: "Descreva uma tarefa que você quer resolver com IA, a entrada necessária e um critério para avaliar a resposta.", placeholder: "Quero transformar… Vou fornecer… Vou conferir se…",
      quiz: { question: "Uma resposta bem escrita pela IA…", options: ["Está correta porque parece profissional.", "Ainda precisa ser conferida antes de ser usada.", "Foi necessariamente copiada de um site."], answer: 1, explanation: "A IA pode produzir texto fluente sem ter confirmado os fatos. Conferir a saída faz parte da tarefa." }, sources: [prompting] },
    { slug: "llms-e-contexto", title: "LLMs, tokens e contexto", minutes: 10,
      intro: "O modelo trabalha com o que recebe. Entender contexto muda a forma como você conversa com ele.",
      sections: [
        { title: "O que é um LLM?", body: "LLM significa modelo de linguagem de grande porte. Ele foi treinado para trabalhar com linguagem e pode produzir, transformar e analisar texto. Modelo e aplicativo são coisas diferentes: o aplicativo organiza a conversa, os arquivos e as ferramentas ao redor do modelo." },
        { title: "Tokens são pedaços de informação", body: "O texto é dividido em unidades chamadas tokens. Um token não corresponde necessariamente a uma palavra. A janela de contexto é o limite de informação que o modelo consegue considerar de uma vez. Uma conversa longa pode ser resumida ou ter partes antigas fora do contexto ativo." },
        { title: "Dê o contexto que importa", body: "Se você pedir uma proposta sem explicar o serviço, a IA terá de preencher lacunas. Informe objetivo, público, material relevante e restrições. Mais texto não significa automaticamente mais qualidade: um briefing organizado costuma ajudar mais do que colar todos os documentos da empresa." }
      ], example: { after: "Contexto: sou designer freelancer e ofereço identidade visual para pequenos negócios. Público: uma cafeteria que está começando. Entrega: um esboço de proposta em 4 seções. Restrições: não inclua preços; destaque as informações que ainda preciso confirmar.", caption: "O briefing reduz o espaço para suposições." },
      steps: ["Escolha uma tarefa e liste três informações indispensáveis.", "Remova detalhes que não ajudam nessa tarefa.", "Inclua no pedido uma instrução para apontar informações ausentes."], task: "Escreva um briefing curto com objetivo, público, contexto e uma restrição.", placeholder: "Objetivo:… Público:… Contexto:… Restrição:…",
      quiz: { question: "Se uma informação importante apareceu muito antes na conversa, o melhor é…", options: ["Pressupor que será lembrada para sempre.", "Enviar mais arquivos sem explicar o objetivo.", "Reapresentar um resumo relevante no pedido atual."], answer: 2, explanation: "O contexto é limitado. Reapresentar o necessário ajuda a manter a tarefa coerente." }, sources: [prompting] },
    { slug: "chatgpt-claude-e-outros", title: "ChatGPT, Claude e outras ferramentas", minutes: 9,
      intro: "Aprenda a escolher uma ferramenta pela tarefa e a comparar resultados sem cair em uma disputa de marcas.",
      sections: [
        { title: "O aplicativo também faz diferença", body: "ChatGPT, Claude e Gemini são exemplos de assistentes. Além dos modelos, eles oferecem interfaces e conjuntos de recursos diferentes. Arquivos, pesquisa, conectores e execução de tarefas dependem do produto, da conta e das permissões. Confira o que está disponível na sua interface antes de seguir um tutorial." },
        { title: "Compare com o mesmo problema", body: "Use exatamente o mesmo briefing em dois assistentes. Avalie precisão, clareza, respeito às restrições e trabalho necessário para revisar. Uma resposta mais longa não é necessariamente melhor. Registre qual resultado você realmente conseguiria usar." },
        { title: "Planeje uma alternativa", body: "Os cursos da Emada são gratuitos, mas recursos das ferramentas externas podem exigir um plano próprio. Quando um recurso não estiver disponível, pratique com o material fictício da aula e registre o plano de execução. Não é necessário contratar uma ferramenta para entender o fluxo." }
      ], example: { after: "Organize estas anotações fictícias em uma pauta de reunião: atualizar catálogo; conferir estoque; revisar entregas atrasadas. Entregue uma tabela com assunto, pergunta a resolver e responsável a definir. Não atribua nomes que não foram fornecidos.", caption: "Use o mesmo pedido em duas ferramentas disponíveis para você." },
      steps: ["Escolha dois assistentes aos quais você tem acesso.", "Envie o mesmo exemplo para ambos, ou faça duas tentativas em um só.", "Compare se ambos respeitaram a instrução de não inventar responsáveis."], task: "Registre qual resultado foi mais útil e um critério objetivo que sustentou sua escolha.", placeholder: "Comparei… O resultado mais útil foi… Meu critério foi…",
      quiz: { question: "Qual é uma comparação justa entre ferramentas?", options: ["Usar o mesmo briefing e os mesmos critérios.", "Escolher a que respondeu com mais palavras.", "Assumir que todos os planos têm os mesmos recursos."], answer: 0, explanation: "Manter entrada e critérios iguais permite avaliar o resultado, e não apenas a apresentação." }, sources: [work, claude] },
    { slug: "primeiro-prompt", title: "Seu primeiro bom prompt", minutes: 12,
      intro: "Um bom prompt funciona como um pedido de trabalho: deixa claro o que fazer e o que significa terminar.",
      sections: [
        { title: "As quatro peças", body: "Comece com tarefa, contexto, formato e critérios. Tarefa: o que fazer. Contexto: as informações que importam. Formato: como entregar. Critérios: as condições que tornam a resposta útil. Você pode acrescentar um exemplo quando for difícil explicar o estilo." },
        { title: "Troque adjetivos por condições", body: "“Faça um texto incrível” não explica o que você espera. “Escreva até 100 palavras, em tom simples, com uma chamada para agendar uma conversa” é verificável. Definir um papel, como “atue como editor”, pode ajudar a direcionar a tarefa, mas não substitui as instruções." },
        { title: "Revise uma variável por vez", body: "Leia a primeira resposta e identifique um problema concreto. Se o texto ficou genérico, acrescente contexto. Se ficou longo, defina um limite. Se inventou informações, forneça a fonte e peça para separar o que está confirmado. Salve as versões que você testou." }
      ], example: { before: "Escreva um e-mail bom.", after: "Escreva um e-mail de apresentação do meu serviço de fotografia de produtos para uma loja de cosméticos. Use até 100 palavras, linguagem direta e uma pergunta final sobre agendar uma conversa. Não invente clientes anteriores, preços ou resultados.", caption: "Você pode montar uma versão sua no Laboratório de prompts." },
      steps: ["Abra o Laboratório e preencha as quatro peças do prompt.", "Copie o pedido e teste em um assistente.", "Ajuste uma instrução com base no resultado."], task: "Cole a versão final do seu prompt e descreva uma melhoria feita após testar.", placeholder: "Meu prompt:… Depois do teste, mudei…",
      quiz: { question: "Qual instrução oferece um critério verificável?", options: ["Seja sensacional.", "Capriche bastante.", "Entregue 3 opções, cada uma com até 20 palavras."], answer: 2, explanation: "Quantidade e tamanho são condições que você consegue conferir na saída." }, sources: [prompting] },
    { slug: "agentes-e-ferramentas", title: "O que muda com um agente?", minutes: 10,
      intro: "Responder uma pergunta e executar um trabalho são capacidades diferentes. Um agente precisa de limites claros para agir.",
      sections: [
        { title: "Do texto à ação", body: "Um agente combina um modelo com instruções e ferramentas para tentar atingir um objetivo. Ele pode escolher uma ação, observar o resultado e decidir o próximo passo. As ferramentas podem buscar um arquivo, consultar uma agenda ou criar um documento, quando essas ações estiverem disponíveis e autorizadas." },
        { title: "Autonomia tem escopo", body: "Compare “organize minha empresa” com “leia estes três arquivos e prepare um relatório”. O segundo pedido delimita entradas e resultado. Também defina onde o agente deve parar: preparar um rascunho é diferente de enviar uma mensagem a clientes." },
        { title: "Defina como lidar com falhas", body: "Se uma conexão falhar, o agente deve informar o problema em vez de inventar o conteúdo. Peça evidências das ações realizadas, como um link para o arquivo criado. A mensagem “concluído” por si só não comprova que o resultado existe." }
      ], example: { after: "Leia os documentos de demonstração que eu anexei e prepare um resumo de pendências. Entregue uma tabela com pendência e trecho de origem. Não envie mensagens nem altere os arquivos. Se faltar uma informação, marque como não informada.", caption: "O objetivo, as ferramentas e o limite de ação ficam explícitos." },
      steps: ["Escolha uma tarefa com dois passos.", "Liste quais ferramentas seriam necessárias.", "Escreva o limite de autonomia e a evidência de conclusão."], task: "Descreva um agente para o seu negócio: objetivo, duas ações permitidas e uma ação que depende de aprovação.", placeholder: "Objetivo:… Pode fazer:… Precisa de aprovação para:…",
      quiz: { question: "Antes de um agente enviar uma proposta real, você deve…", options: ["Definir a autorização e revisar os dados e o destinatário.", "Confiar apenas na frase “está pronto”.", "Compartilhar todas as credenciais por precaução."], answer: 0, explanation: "A autorização deve corresponder à ação concreta, e o resultado precisa ser verificável." }, sources: [work, mcp] },
    { slug: "projeto-basico", title: "Mini projeto: seu assistente de trabalho", minutes: 15,
      intro: "Junte o que aprendeu para criar um briefing reutilizável para uma tarefa real do seu dia a dia.",
      sections: [
        { title: "Escolha uma entrega útil", body: "Pode ser uma pauta semanal, uma proposta comercial sem preços ou uma lista de perguntas para atender um cliente. Escolha algo pequeno o suficiente para você testar em poucos minutos. Use dados fictícios nesta primeira versão." },
        { title: "Crie uma ficha de trabalho", body: "Registre objetivo, entrada, instruções, formato, critérios e limites. Faça um teste com informação completa e outro em que falte um dado importante. Observe se o assistente pede o que falta ou se tenta adivinhar." },
        { title: "Guarde o que funcionou", body: "A versão final deve permitir que outra pessoa entenda como repetir a tarefa. Inclua uma amostra de entrada e uma lista curta de revisão. Essa ficha será a base da sua skill no módulo intermediário." }
      ], example: { after: "Objetivo: transformar pedidos fictícios de clientes em um briefing. Entrada: mensagem do cliente. Saída: tabela com objetivo, prazo, entregáveis e dúvidas. Se não houver prazo, registre “a confirmar”. Critérios: nenhuma informação inventada; perguntas específicas; texto em português. Limite: preparar o briefing, sem enviar resposta ao cliente.", caption: "Um pequeno processo documentado já é um resultado útil." },
      steps: ["Escreva sua ficha de trabalho.", "Teste com uma entrada completa e outra incompleta.", "Revise a saída e registre a versão aprovada por você."], task: "Entregue sua ficha e registre o que aconteceu no teste com informação ausente.", placeholder: "Minha ficha:… No teste sem… o assistente… Eu ajustei…",
      quiz: { question: "Por que testar uma entrada incompleta?", options: ["Para obrigar a IA a inventar uma solução.", "Para conferir como ela lida com o que não sabe.", "Para tornar a resposta mais longa."], answer: 1, explanation: "Testes com lacunas mostram se o processo identifica o que precisa ser confirmado." }, sources: [prompting] }
  ] },
  { slug: "automacoes", number: "02", title: "Menos repetição. Mais ação.", subtitle: "Conecte. Organize. Automatize.", description: "Conecte ferramentas, crie skills e delegue fluxos que trabalham com você. Um passo de cada vez.", level: "Intermediário", tags: ["Work", "Skills", "MCP", "Automações"], lessons: [
    { slug: "modo-work", title: "Trabalhando com Work e Cowork", minutes: 12,
      intro: "Saia da pergunta isolada para uma tarefa com arquivos, etapas e uma entrega que você consegue revisar.",
      sections: [
        { title: "Delegue um resultado", body: "ChatGPT Work permite delegar tarefas mais extensas e receber resultados para revisão. No ecossistema Claude, Cowork oferece uma experiência de trabalho com tarefas e ferramentas. As interfaces e disponibilidades variam; use o guia oficial vinculado ao final para conferir sua conta." },
        { title: "Prepare uma pasta de exercício", body: "Crie três arquivos fictícios com ideias de posts para uma pequena loja. Dê nomes claros e remova qualquer dado de cliente. Peça uma organização em calendário editorial. Defina público, período, formato e onde a entrega deve aparecer." },
        { title: "Confira a entrega", body: "Abra o arquivo produzido. Verifique se há datas repetidas, ideias ausentes ou informações inventadas. Faça uma correção específica e peça uma nova versão. Se você estiver usando apenas um chat, cole os três textos e peça uma tabela para praticar o mesmo raciocínio." }
      ], example: { after: "Organize estes três arquivos fictícios em um calendário editorial de uma semana. Crie uma tabela com dia, tema, ideia e arquivo de origem. Use apenas as ideias fornecidas. Entregue um rascunho para minha revisão e não publique nada.", caption: "Uma entrega concreta facilita a revisão do trabalho." },
      steps: ["Prepare três notas fictícias e abra Work, Cowork ou um chat disponível.", "Envie o briefing com o formato de entrega.", "Abra o resultado e confira pelo menos três itens com as fontes."], task: "Registre seu briefing, o formato entregue e uma correção que você pediu.", placeholder: "Pedi… Recebi… Ao conferir, ajustei…",
      quiz: { question: "O que comprova a conclusão desta tarefa?", options: ["Uma promessa de que o arquivo será criado.", "O tempo que o agente passou trabalhando.", "Uma entrega acessível e conferida com as fontes."], answer: 2, explanation: "Uma entrega verificável permite distinguir execução real de uma descrição do que seria feito." }, sources: [work, computer] },
    { slug: "plugins-e-conectores", title: "Conecte seu primeiro plugin", minutes: 15,
      intro: "Dê ao assistente acesso a uma ferramenta específica e teste uma tarefa pequena de leitura.",
      sections: [
        { title: "Um pacote de capacidades", body: "Plugins podem reunir skills e conectores. Um conector permite trabalhar com um serviço externo, conforme o acesso concedido. Instalar um plugin não significa que a conta externa já está conectada: pode existir uma etapa de autenticação separada." },
        { title: "Conecte com um objetivo", body: "No ChatGPT, abra a área de Plugins e procure um serviço que você usa. No Claude, procure em Customize a área de conectores ou plugins. Confira o desenvolvedor e as permissões solicitadas. Conecte a conta de teste e comece com uma consulta a um arquivo fictício específico." },
        { title: "Teste e revise o acesso", body: "Peça o título e um resumo do documento de teste, com link para a fonte. Compare com o original. Depois localize onde desconectar o serviço. Se o conector não estiver disponível, documente o fluxo com uma captura textual dos passos esperados, sem fornecer credenciais à plataforma." }
      ], example: { after: "No serviço conectado, localize o documento de demonstração “Briefing da cafeteria”. Leia somente esse documento e liste as três principais pendências, com o link da fonte. Não edite nem compartilhe arquivos. Se não o encontrar, me avise.", caption: "A primeira conexão deve ter um teste pequeno e fácil de verificar." },
      steps: ["Encontre o conector oficial de um serviço e confira suas permissões.", "Conecte uma conta de teste ou descreva o processo se não estiver disponível.", "Faça uma consulta de leitura e localize a opção de desconectar."], task: "Registre o serviço escolhido, as permissões observadas e como você conferiu a consulta. Não cole senhas ou tokens.", placeholder: "Serviço:… Permissões:… Teste:… Como desconectar:…",
      quiz: { question: "Instalar um plugin e conectar uma conta…", options: ["Podem ser etapas diferentes.", "Dão acesso automático a todos os seus serviços.", "Dispensam a revisão de permissões."], answer: 0, explanation: "O pacote disponibiliza capacidades; a conexão autoriza o acesso a uma conta externa." }, sources: [plugins, {label:"Claude · Diretório de plugins",url:"https://support.claude.com/en/articles/14328846-browse-skills-connectors-and-plugins-in-one-directory"}] },
    { slug: "primeiro-mcp", title: "MCP: a conexão por trás da conexão", minutes: 15,
      intro: "Entenda o papel do protocolo e aprenda a avaliar uma conexão antes de usar as ferramentas que ela oferece.",
      sections: [
        { title: "Uma linguagem comum para ferramentas", body: "MCP, Model Context Protocol, é um padrão aberto para conectar aplicações de IA a ferramentas e fontes de dados. O aplicativo é o host; um servidor MCP oferece capacidades. O protocolo não é um modelo e não dá inteligência ou autorização ilimitada por conta própria." },
        { title: "Local ou remoto", body: "Um servidor local roda na sua máquina; um remoto é acessado pela rede. Os detalhes de instalação dependem do aplicativo. Para este exercício, prefira um servidor remoto oficial, documentado pelo fornecedor de um serviço de teste. Não execute um comando de instalação de origem desconhecida." },
        { title: "Um teste com escopo limitado", body: "Na área de conectores personalizados do aplicativo, quando disponível, use a URL fornecida pela documentação oficial do serviço. Conclua a autenticação, confira as ferramentas oferecidas e peça uma consulta de leitura. Se faltar o recurso na sua conta, faça o desenho da conexão: aplicativo, servidor, conta, ferramenta e resultado esperado." }
      ], example: { after: "Use somente a ferramenta de busca do conector de teste para localizar o documento “Catálogo demonstrativo”. Mostre título e link. Não crie, edite ou exclua registros. Se a ferramenta não estiver disponível, explique o que está faltando.", caption: "A URL do servidor deve vir do fornecedor. Não use URLs ilustrativas como se fossem serviços reais." },
      steps: ["Identifique o aplicativo e a documentação de um servidor MCP oficial.", "Liste uma ferramenta de leitura e a permissão necessária.", "Teste a consulta, ou desenhe o fluxo se não puder conectar."], task: "Descreva aplicativo → servidor MCP → ferramenta → resultado e inclua o link da documentação consultada.", placeholder: "Aplicativo:… Servidor:… Ferramenta:… Resultado:… Documentação:…",
      quiz: { question: "Um servidor MCP é…", options: ["Um novo modelo que substitui o LLM.", "Uma forma de oferecer ferramentas ou contexto a um aplicativo compatível.", "Uma autorização para acessar qualquer conta."], answer: 1, explanation: "MCP padroniza a conexão. Acesso e capacidades continuam dependendo do servidor e das permissões." }, sources: [mcp, claude] },
    { slug: "crie-uma-skill", title: "Transforme seu processo em uma skill", minutes: 15,
      intro: "Uma skill guarda instruções de um trabalho recorrente para você não precisar explicar tudo de novo.",
      sections: [
        { title: "Uma receita reutilizável", body: "Skills combinam instruções com recursos de apoio para um tipo de tarefa. Elas ensinam como executar o trabalho. Um conector oferece acesso a uma ferramenta; uma skill orienta como usar capacidades disponíveis. Uma skill pode ser útil mesmo sem um conector." },
        { title: "Escreva quando e como usar", body: "Recupere a ficha do mini projeto básico. Dê um nome específico, explique quando aplicar e liste as etapas. Defina a entrada, o formato de saída e o tratamento de informações ausentes. Uma descrição ampla demais dificulta identificar a tarefa certa." },
        { title: "Teste a receita", body: "Crie um arquivo SKILL.md com seu procedimento e siga as instruções do seu aplicativo para adicioná-lo, quando houver suporte. Teste com duas entradas diferentes. Você também pode colar as instruções no início de um chat e verificar se o processo é reproduzível." }
      ], example: { after: "---\nname: briefing-de-cliente\ndescription: Organiza uma mensagem de cliente em briefing de projeto.\n---\n1. Leia a mensagem fornecida.\n2. Extraia objetivo, prazo e entregáveis.\n3. Marque dados ausentes como “a confirmar”.\n4. Entregue uma tabela e até 3 perguntas objetivas.\n5. Não envie mensagens ao cliente.", caption: "Exemplo didático de SKILL.md. A forma de instalação depende da ferramenta." },
      steps: ["Adapte a ficha do módulo básico para uma receita em etapas.", "Defina quando usar e o que fazer se faltarem dados.", "Teste com duas mensagens fictícias e revise o procedimento."], task: "Cole sua skill e descreva um ajuste feito depois dos testes.", placeholder: "Nome:… Quando usar:… Etapas:… Ajuste após testar:…",
      quiz: { question: "Qual é a principal função de uma skill?", options: ["Guardar uma receita de trabalho reutilizável.", "Substituir o login de um serviço.", "Garantir que toda resposta esteja correta."], answer: 0, explanation: "A skill orienta um procedimento. Ela não concede acesso externo nem elimina a necessidade de revisão." }, sources: [skills, {label:"Claude · Usar skills",url:"https://support.claude.com/en/articles/12512180-use-skills-in-claude"}] },
    { slug: "computer-use", title: "Computer use: IA usando a interface", minutes: 12,
      intro: "Quando uma tarefa depende de uma tela, um agente pode interagir com a interface. Você precisa definir onde ele pode agir.",
      sections: [
        { title: "Cliques também são ações", body: "Computer use permite que um agente interaja com software por meio da interface, como clicar e digitar. No Cowork, o recurso pode complementar conectores e navegação. A disponibilidade depende da conta e do ambiente; consulte a documentação atual antes do teste." },
        { title: "Monte uma área de prática", body: "Use um documento fictício ou o Laboratório da Emada. Peça ao agente para preencher campos com dados de demonstração e parar antes de qualquer envio externo. Feche documentos privados desnecessários e mantenha apenas o contexto de teste disponível." },
        { title: "Verifique o estado da tela", body: "Um clique não comprova que a ação funcionou. Confira se o campo ficou preenchido e se o resultado esperado está visível. Se a interface mudou ou aparecer um pedido de acesso inesperado, pause e esclareça o próximo passo. Se você não tiver computer use, execute manualmente os passos e anote onde seria necessário conferir o estado." }
      ], example: { after: "Abra o Laboratório da Emada e preencha o contexto de um prompt com os dados fictícios desta mensagem. Mostre a prévia e pare para eu revisar. Não abra outros sites, não entre em contas e não envie mensagens.", caption: "O exercício termina em uma prévia, antes de qualquer publicação." },
      steps: ["Escolha uma página de teste sem dados sensíveis.", "Escreva os campos a preencher e o ponto de parada.", "Confira visualmente o resultado antes de seguir."], task: "Registre o roteiro de interação, o ponto de parada e como conferiu o resultado.", placeholder: "Tela de teste:… Passos:… Parar antes de:… Verificação:…",
      quiz: { question: "Depois que o agente clica em um botão, o próximo passo é…", options: ["Presumir que a tarefa terminou.", "Clicar várias vezes sem observar.", "Conferir o estado visível e o resultado da ação."], answer: 2, explanation: "A interface pode demorar, mudar ou apresentar um erro. A observação confirma o efeito da ação." }, sources: [computer] },
    { slug: "cron-jobs", title: "Agendamentos e cron jobs", minutes: 15,
      intro: "Uma automação recorrente precisa de mais do que um horário. Precisa saber o que fazer e quando te chamar.",
      sections: [
        { title: "O gatilho é só o começo", body: "Um agendamento dispara uma tarefa em um horário ou frequência. Alguns assistentes permitem definir isso em linguagem natural; plataformas de hospedagem podem usar expressões cron. O agendador dispara a execução, mas não garante que a fonte esteja acessível ou que a tarefa termine com sucesso." },
        { title: "Horário, fuso e ambiente", body: "Declare o fuso explicitamente. Uma rotina às 9h em São Paulo é diferente de 9h UTC. Automações locais podem depender de um computador disponível; execuções em nuvem dependem dos recursos oferecidos pelo serviço. Confira essas condições na ferramenta que você escolheu." },
        { title: "Dê uma regra para avisos", body: "Defina o que conta como novidade e o que fazer quando nada mudou. Evite enviar o mesmo aviso todos os dias. Para começar, faça uma execução manual, revise o resultado e só então ative a recorrência. Aprenda também como pausar ou excluir o agendamento." }
      ], example: { after: "Toda segunda-feira às 9h, no fuso America/Sao_Paulo, consulte a fonte pública que eu indicar e prepare um resumo de novidades desde a última consulta. Inclua links. Avise apenas se houver novidades ou falha de acesso. Não publique nem envie o resumo a outras pessoas. Faça primeiro uma execução de teste.", caption: "No cron tradicional, “0 9 * * 1” significa segunda-feira às 9h no fuso usado pelo agendador." },
      steps: ["Abra o construtor de fluxos do Laboratório e escolha uma recorrência.", "Defina o fuso, a fonte e a regra de aviso.", "Teste manualmente e identifique onde pausar antes de ativar na ferramenta."], task: "Escreva a instrução de agendamento com frequência, fuso, ação, regra de aviso e forma de pausar.", placeholder: "Quando:… Fuso:… Fazer:… Avisar se:… Pausar em:…",
      quiz: { question: "Um cron configurado para 9h…", options: ["Sempre roda às 9h no horário de quem o criou.", "Depende do fuso utilizado pelo agendador.", "Garante que a tarefa será concluída."], answer: 1, explanation: "O horário deve ser interpretado no fuso do agendador. Execução e sucesso são eventos diferentes." }, sources: [cron, {label:"Vercel · Cron Jobs",url:"https://vercel.com/docs/cron-jobs"}] },
    { slug: "fluxo-com-aprovacao", title: "Um fluxo com aprovação humana", minutes: 15,
      intro: "Conecte entrada, processamento e revisão em um processo que você consegue acompanhar e repetir.",
      sections: [
        { title: "Desenhe o caminho completo", body: "Um fluxo simples pode ser: receber uma nota de reunião, extrair pendências, gerar um rascunho e pedir revisão. A saída de uma etapa vira entrada da seguinte. Escreva o que cada etapa recebe e produz antes de escolher as ferramentas." },
        { title: "Coloque a revisão no lugar certo", body: "Revisar depois de publicar é tarde demais para evitar um erro. Posicione a aprovação entre o rascunho e a ação externa. Mostre ao revisor o conteúdo, a fonte e a ação proposta. Se houver rejeição, volte à etapa de ajuste." },
        { title: "Planeje repetição e falha", body: "Uma rotina pode rodar duas vezes. Use um identificador da entrada para reconhecer o que já foi processado. Se uma etapa falhar, registre o motivo e não avance como se tivesse dado certo. O feed de notícias desta plataforma segue essa lógica: coleta, fila e aprovação antes da publicação." }
      ], example: { after: "Entrada: nota fictícia da reunião de hoje. Etapa 1: extrair decisões e pendências com trechos de origem. Etapa 2: preparar rascunho de atualização. Etapa 3: aguardar minha aprovação do conteúdo e dos destinatários. Em caso de rejeição, revisar o rascunho. Não enviar automaticamente.", caption: "A revisão é parte explícita do fluxo." },
      steps: ["Monte um fluxo de quatro etapas no Laboratório.", "Inclua aprovação antes de uma ação externa.", "Descreva o que acontece em caso de falha ou execução duplicada."], task: "Entregue seu fluxo, quem aprova e as regras para falha e repetição.", placeholder: "Entrada →… → revisão por… →… Se falhar:… Se repetir:…",
      quiz: { question: "Onde entra a aprovação de uma mensagem para clientes?", options: ["Antes do envio, com conteúdo e destinatários visíveis.", "Depois do envio, para corrigir se alguém reclamar.", "Só na primeira execução, independentemente do conteúdo."], answer: 0, explanation: "A aprovação precisa cobrir o conteúdo e a ação que realmente serão executados." }, sources: [work, cron] },
    { slug: "projeto-intermediario", title: "Mini projeto: sua primeira automação", minutes: 20,
      intro: "Monte um processo pequeno, teste ponta a ponta e documente como alguém pode operar e interromper a automação.",
      sections: [
        { title: "Escolha um caso de uso", body: "Escolha entre resumo semanal de fontes públicas, organização de notas ou preparação de conteúdo. Use no máximo uma conexão externa na primeira versão. O objetivo é terminar um fluxo verificável, não acumular ferramentas." },
        { title: "Combine as peças", body: "Escreva um briefing, reúna as regras em uma skill e indique o conector ou MCP necessário. Defina gatilho, saída e aprovação. Use computer use apenas se a tarefa exigir interação com a interface. Se um recurso estiver indisponível, documente o passo manual equivalente." },
        { title: "Faça três testes", body: "Teste uma entrada válida, uma entrada sem informação suficiente e a mesma entrada repetida. Registre o resultado de cada caso. Confira quem pode acessar a saída, como pausar e como voltar à execução manual. Ative a recorrência somente depois de revisar esses testes." }
      ], example: { after: "Projeto: radar semanal de novidades para minha loja. Fonte: uma página pública escolhida por mim. Processo: consultar → comparar com a última consulta → preparar até 3 itens com links → aguardar minha revisão. Frequência: segunda às 9h, America/Sao_Paulo. Se a fonte falhar, avisar; se não houver novidade, não repetir itens. Entrega: rascunho, sem publicação automática.", caption: "Você termina com um processo que pode explicar, testar e interromper." },
      steps: ["Documente seu objetivo, as ferramentas e o fluxo.", "Execute os três testes: normal, incompleto e repetido.", "Registre como revisar, pausar e executar manualmente."], task: "Entregue a ficha do projeto, os resultados dos três testes e o procedimento de pausa.", placeholder: "Projeto:… Fluxo:… Teste normal:… Incompleto:… Repetido:… Pausa:…",
      quiz: { question: "Quando a automação está pronta para uma primeira recorrência?", options: ["Quando o desenho tem muitas etapas.", "Quando os testes passaram, a saída foi revisada e há como pausar.", "Quando a IA diz que nenhuma revisão será necessária."], answer: 1, explanation: "Prontidão exige testes, revisão e controle da operação. Ela não depende da quantidade de ferramentas." }, sources: [work, cron, mcp] }
  ] }
];
// Keep the original basics addressable: stored exercises must retain their meaning.
export const archivedModules = [originalModules[0]];
export const archivedLessons = archivedModules.flatMap(m => m.lessons);
export const modules: CourseModule[] = [basicModule, ...originalModules.slice(1)];
export const allLessons = modules.flatMap(m => m.lessons);
export const totalMinutes = allLessons.reduce((sum, lesson) => sum + lesson.minutes, 0);
export function findLesson(slug: string) { const foundModule = [...modules, ...archivedModules].find(m => m.lessons.some(l => l.slug === slug)); const lesson = foundModule?.lessons.find(l => l.slug === slug); return { module: foundModule, lesson }; }
export function nextLesson(slug: string) { return allLessons[allLessons.findIndex(l => l.slug === slug) + 1]; }
export const glossary = [
  { term: "IA generativa", definition: "Sistemas que produzem conteúdo, como texto, imagem ou áudio, a partir de instruções e contexto.", category: "Fundamentos" },
  { term: "LLM", definition: "Modelo de linguagem de grande porte. Trabalha com padrões de linguagem para gerar e transformar texto.", category: "Fundamentos" },
  { term: "Prompt", definition: "O pedido que orienta a IA: tarefa, contexto, formato esperado e critérios de qualidade.", category: "Fundamentos" },
  { term: "Token", definition: "Uma unidade de informação processada pelo modelo. Pode ser uma palavra, parte dela ou um sinal.", category: "Fundamentos" },
  { term: "Janela de contexto", definition: "O limite de informações que o modelo pode considerar de uma vez durante a tarefa.", category: "Fundamentos" },
  { term: "Alucinação", definition: "Uma resposta que apresenta informação inventada ou incorreta como se fosse um fato.", category: "Fundamentos" },
  { term: "Agente", definition: "Sistema que usa um modelo, instruções e ferramentas para executar passos em direção a um objetivo.", category: "Automações" },
  { term: "Skill", definition: "Instruções e recursos reutilizáveis que orientam como realizar um tipo específico de trabalho.", category: "Automações" },
  { term: "Plugin", definition: "Pacote que pode reunir skills, conectores e outras capacidades instaláveis no aplicativo.", category: "Conexões" },
  { term: "Conector", definition: "Integração que dá acesso a um serviço externo dentro das permissões concedidas à conta.", category: "Conexões" },
  { term: "MCP", definition: "Model Context Protocol: padrão aberto para conectar aplicativos de IA a ferramentas e fontes de dados.", category: "Conexões" },
  { term: "Computer use", definition: "Interação de um agente com a interface de um software, por exemplo clicando e preenchendo campos.", category: "Automações" },
  { term: "Cron job", definition: "Tarefa acionada por um agendamento recorrente. O horário depende do fuso configurado no agendador.", category: "Automações" },
  { term: "Aprovação humana", definition: "Etapa em que uma pessoa revisa o resultado e autoriza a próxima ação do fluxo.", category: "Automações" }
];
export const promptTemplates = [
  { title: "Organizar um briefing", category: "Trabalho", text: "Transforme a mensagem abaixo em um briefing. Extraia objetivo, público, prazo e entregáveis. Marque o que não foi informado como ‘a confirmar’. Entregue uma tabela e até 3 perguntas para esclarecer lacunas. Mensagem: [cole um exemplo fictício]." },
  { title: "Planejar uma semana de conteúdo", category: "Empreendedorismo", text: "Crie um calendário de 5 posts para [negócio] sobre [tema], voltado a [público]. Entregue dia, ideia, formato e objetivo. Use tom [tom]. Não invente estatísticas, depoimentos ou resultados. Apresente como rascunho para revisão." },
  { title: "Revisar antes de publicar", category: "Trabalho", text: "Revise este rascunho quanto a clareza, repetição e afirmações sem fonte. Liste os problemas e proponha ajustes pontuais. Não acrescente fatos novos nem publique. Texto: [cole o rascunho]." },
  { title: "Preparar uma proposta", category: "Empreendedorismo", text: "Prepare um esboço de proposta de [serviço] para [público]. Use 4 seções: problema, entregáveis, etapas e pontos a confirmar. Não invente preços, prazos ou clientes anteriores. Use somente este contexto: [contexto]." },
  { title: "Criar uma rotina de pesquisa", category: "Automações", text: "Toda [frequência], às [horário], no fuso [fuso], consulte [fonte pública] e prepare um resumo das novidades desde a última execução. Inclua links e datas. Evite itens repetidos. Avise apenas sobre novidades ou falhas. Não publique. Faça um teste antes de ativar a recorrência." },
  { title: "Conferir uma conexão", category: "Conexões", text: "Use o conector [serviço] apenas para localizar o documento fictício [nome]. Retorne título, link e um resumo de até 3 linhas. Não altere, compartilhe ou exclua arquivos. Se não tiver acesso, explique o que está faltando." }
];
