"use client";
import { useState, useTransition } from "react";
import { ArrowUpRight, Check, LoaderCircle, RefreshCw, RotateCcw, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { moderateNews, syncNews } from "@/app/actions/news";
import type { NewsItem } from "@/lib/feed-parser";
export function AdminNews({ items }: { items: NewsItem[] }) {
  const [status, setStatus] = useState("pending"); const [message, setMessage] = useState(""); const [busy, startTransition] = useTransition();
  const filtered = items.filter(item => item.status === status);
  return <><div className="admin-header"><div className="filter-bar mb-0!">{[{ id: "pending", label: "Para revisar" }, { id: "approved", label: "Publicadas" }, { id: "rejected", label: "Rejeitadas" }].map(tab => <button key={tab.id} className={`filter-button ${status === tab.id ? "selected" : ""}`} onClick={() => setStatus(tab.id)} aria-pressed={status === tab.id}>{tab.label} · {items.filter(item => item.status === tab.id).length}</button>)}</div><Button variant="outline" disabled={busy} onClick={() => startTransition(async () => { const result = await syncNews(); setMessage(result.message); })}>{busy ? <LoaderCircle size={15} className="animate-spin"/> : <RefreshCw size={15}/>}Coletar agora</Button></div>{message && <p className="admin-status" role="status">{message}</p>}<div className="admin-news-list">{filtered.map(item => <article className="admin-news-card" key={item.id}><div className="admin-news-meta"><span>{item.source}</span><span>·</span><time dateTime={item.published_at}>{new Date(item.published_at).toLocaleDateString("pt-BR", { timeZone: "UTC" })}</time></div><h2>{item.title}</h2><a href={item.url} target="_blank" rel="noreferrer">Ler matéria original <ArrowUpRight size={14}/></a><div className="admin-news-actions">{item.status !== "approved" && <Button size="sm" disabled={busy} onClick={() => startTransition(async () => { setMessage((await moderateNews(item.id, "approved")).message); })}><Check size={14}/>Aprovar e publicar</Button>}{item.status !== "rejected" && <Button size="sm" variant="outline" disabled={busy} onClick={() => startTransition(async () => { setMessage((await moderateNews(item.id, "rejected")).message); })}><X size={14}/>{item.status === "approved" ? "Retirar do ar" : "Rejeitar"}</Button>}{item.status !== "pending" && <Button size="sm" variant="ghost" disabled={busy} onClick={() => startTransition(async () => { setMessage((await moderateNews(item.id, "pending")).message); })}><RotateCcw size={14}/>Voltar à revisão</Button>}</div></article>)}</div>{!filtered.length && <div className="news-empty"><Check size={25} className="pink"/><div><h3>{status === "pending" ? "Nenhuma notícia aguardando revisão." : "Nenhuma notícia nesta lista."}</h3><p>A coleta mantém os itens em revisão. Só notícias aprovadas aparecem para os alunos.</p></div></div>}</>;
}
